/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_webshop_controller_HomeController */

#ifndef _Included_com_webshop_controller_HomeController
#define _Included_com_webshop_controller_HomeController
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_webshop_controller_HomeController
 * Method:    readData
 * Signature: ([B)Lcom/webshop/controller/CaffData;
 */
JNIEXPORT jobject JNICALL Java_com_webshop_controller_HomeController_readData
  (JNIEnv *, jobject, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
