/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_nullpointerexception_ParserJNI */

#ifndef _Included_com_nullpointerexception_ParserJNI
#define _Included_com_nullpointerexception_ParserJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_nullpointerexception_ParserJNI
 * Method:    readData
 * Signature: ([B)Lcom/nullpointerexception/CaffData;
 */
JNIEXPORT jobject JNICALL Java_com_nullpointerexception_ParserJNI_readData
  (JNIEnv *, jobject, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
